// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ServerBackend.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    partial class ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileJson")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ProfileJson");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("UsernameAccount", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("UsernameAccount", b =>
                {
                    b.OwnsOne("ProfileServer.Models.UserAccount", "Account", b1 =>
                        {
                            b1.Property<string>("UsernameAccountUsername")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("UsernameAccountUsername");

                            b1.HasIndex("Id");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("UsernameAccountUsername");
                        });

                    b.Navigation("Account")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
